# Generated by Django 3.1.7 on 2021-11-17 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_auto_20211010_1846'),
        ('main', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='followers', through='actions.Follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
