# Generated by Django 3.1.7 on 2021-09-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-id',), 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
    ]
